// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edlgycrfuddvcfugmylc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkbGd5Y3JmdWRkdmNmdWdteWxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4Mzg1ODQsImV4cCI6MjA3MDQxNDU4NH0.YsyWkv1AKo3MZK3_dGMR-EnnDe0flWQ-JMyOSIJiVR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});